# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sidemenuV3' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNBoilerPlate

  

  platform :ios, '9.0'
  target 'sidemenuV3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sidemenuV3-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNBoilerPlate-tvOS

  target 'sidemenuV3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
